### ISSUE TITLE
How to activate extension?

### ISSUE THREAD

**Issue by ghost** [ginfuru/vscode-jekyll-snippets#3]
I've tried a bunch of stuff (new files, look in the command palette, try different file extensions etc.) to get this extension to kick in but nothing seems to bring up any of the snippets it provides. The documentation doesn't do much in describing exactly how this extension is supposed to work.  
  
The documentation for the two extensions that it's based on doesn't help much either. I'm running the latest VS code on Debian if that's of any relevance.

**Comment by edheltzel** [comment]
What file extension are you using?

**Comment by ghost** [comment]
I've tried both html and md files in the root of my project and html in the layouts folder. 



-------- Original message --------From: Ed Heltzel <notifications@github.com> Date: 1/3/17  22:22  (GMT+01:00) To: ginfuru/vscode-jekyll-snippets <vscode-jekyll-snippets@noreply.github.com> Cc: Jesper Hess Nielsen <jesper@graffen.dk>, Author <author@noreply.github.com> Subject: Re: [ginfuru/vscode-jekyll-snippets] How to activate extension? (#3) 
What file extension are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ginfuru/vscode-jekyll-snippets","title":"ginfuru/vscode-jekyll-snippets","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ginfuru/vscode-jekyll-snippets"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ginfuru in #3: What file extension are you using? "}],"action":{"name":"View Issue","url":"https://github.com/ginfuru/vscode-jekyll-snippets/issues/3#issuecomment-270228302"}}}

**Comment by edheltzel** [comment]
Gotcha... try changing the syntax to liquid. 
If you don't have it install the Liquid syntax from Shopify. 

Let me know if that resolves it, so I can update the readme.

**Comment by ghost** [comment]
Ah, I'll try this first thing tomorrow morning and let you know. Thanks for the quick response! 
-------- Original message --------From: Ed Heltzel <notifications@github.com> Date: 1/3/17  22:37  (GMT+01:00) To: ginfuru/vscode-jekyll-snippets <vscode-jekyll-snippets@noreply.github.com> Cc: Jesper Hess Nielsen <jesper@graffen.dk>, Author <author@noreply.github.com> Subject: Re: [ginfuru/vscode-jekyll-snippets] How to activate extension? (#3) 
Gotcha... try changing the syntax to liquid.

If you don't have it install the Liquid syntax from Shopify.
Let me know if that resolves it, so I can update the readme.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ginfuru/vscode-jekyll-snippets","title":"ginfuru/vscode-jekyll-snippets","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ginfuru/vscode-jekyll-snippets"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ginfuru in #3: Gotcha... try changing the syntax to liquid. \nIf you don't have it install the Liquid syntax from Shopify. \n\nLet me know if that resolves it, so I can update the readme. "}],"action":{"name":"View Issue","url":"https://github.com/ginfuru/vscode-jekyll-snippets/issues/3#issuecomment-270231873"}}}

**Comment by edheltzel** [comment]
👍 No problem.

**Comment by ghost** [comment]
Installing the "Liquid Language Support" extension from Niel Ding and changing the syntax highlighter (Ctrl-K M) to Liquid did the trick. Only problem is the syntax highlighter isn't really kicking in, everything is just plain gray text now. But that's not likely an issue with this plugin :) Thanks!

**Comment by edheltzel** [comment]
Nice! 
What color scheme do you use?

**Comment by edheltzel** [comment]
@graffen **Thanks for creating the issue 👍  made me troll the VS Code docs** 
So I added `extensionDependencies` to the package manifest for the extension so Liquid Lang. Support will also install when installing the Jekyll Snippets. Also works for uninstall.
