### ISSUE TITLE
Jekyll document autoformat problem.

### ISSUE THREAD

**Issue by Serhioromano** [ginfuru/vscode-jekyll-snippets#8]
Please look here https://github.com/Microsoft/vscode/issues/24088

Is this an issue for this plugin?

**Comment by edheltzel** [comment]
@Serhioromano I can confirm the formatting issues with `"editor.formatOnSave": true` for `HTML` files with Front-Matter. But, if I  change the grammar of the file from plain `HTML` to  `Liquid HTML` The formatting issues go away.

**Comment by Serhioromano** [comment]
Yes the problem goes away but formatting also goes away. It no longer format this document. So I have to manually format it with is inconvenient.

May be you have to add formatting options for Liquid HTML documents.

**Comment by edheltzel** [comment]
@Serhioromano I'll have to dig into the docs of VS Code a little more to see how to get HTML formatting for the Liquid Languages Support - But that might need to be referenced in the repo.

**Comment by Serhioromano** [comment]
I added new comment in VS Code topic because I think it should be general formatting issue.

Also there is a thread in Beautifier repository
https://github.com/beautify-web/js-beautify/issues/510

**Comment by jel111** [comment]
Is there some problem with Handlebars being the same syntax? I forgot the term for changing that so the syntax is different. Do you know what that is called? Thanks!

**Comment by edheltzel** [comment]
@jel111 ~I believe it is really more of a front-matter issue vs the curly brackets~
check out this: https://github.com/Microsoft/vscode/issues/24088#issuecomment-296434106

As for the term, I think you might be saying grammar? _(VSCode calls it “Language Mode”)_

**Comment by edheltzel** [comment]
@Serhioromano as I mentioned in https://github.com/Microsoft/vscode/issues/24088#issuecomment-302942862

---

### For anyone else having formatting issues:
consider installing VSCode [prettydiff extension](https://marketplace.visualstudio.com/items?itemName=HexcodeTechnologies.vscode-prettydiff) to format your `liquid tags`

**Comment by jel111** [comment]
Thanks.

**Comment by michellecarrasco** [comment]
Thanks for the tip @ginfuru 
However, this is not working for frontmatter tags.
You can try this example:

```
--- 
layout: default 
---

<div class="row">
    <div class="large-2 column">
        <ul class="menu vertical">
            {% assign sorted = site.docs | sort:"order" %} {% for post in sorted %}
            <li class="{% if page.url == post.url %}active{% endif %}"><a href={{ post.url }}>{{ post.menu }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="large-10 column">
        <header class="post-header">
            <h1 class="post-title">{{ page.title | escape }}</h1>
        </header>
        {{ content }}
    </div>
</div>
```

on the prettydiff demo site: http://prettydiff.com/
Note: You have to try with the beautify function that you can select with the top radio button.

Here is the (non-working with Jekyll 3.7.3) result:
```
--- layout: default ---

<div class="row">
...
</div>
```

Note: I also tried with the vscode plugin and I got the same result.
Note 2: The demo site doesn't seems to use the last build but it was built after the GH issues were fixed: https://github.com/prettydiff/prettydiff/issues?utf8=%E2%9C%93&q=liquid%20
