### ISSUE TITLE
What functionality does this actually add?

### ISSUE THREAD

**Issue by janpio** [ginfuru/vscode-jekyll-snippets#9]
I was looking for VS Code extensions to help me working with my Jekyll site. 
What exactly does this extension add? 
What functionality is available where when installed?

**Comment by edheltzel** [comment]
its provides snippets for Liquid integers, for loops, arrays, filters, strings ... So pretty much everything that is found here: https://learn.cloudcannon.com/jekyll-cheat-sheet/

When you install the extension it also installs Liquid Syntax Extension - so you liquid tags show up with your syntax highlighting. 

Does that clear it up?

**Comment by janpio** [comment]
Not really... never used Snippets in @Code to be honest. How do I use these exactly?

(You might want to add this information to the README for newbs like me ;) )

**Comment by edheltzel** [comment]
Gotcha - umm assuming you're new to Jekyll in general? 

_Keep in mind - I have snippets show up at the top of Intellisence, which you can configre with your Editor setting or workspace settings_ 

Here is a quick gif: 

![kapture 2017-09-27 at 12 00 03](https://user-images.githubusercontent.com/402910/30924037-907338b6-a37b-11e7-98bf-2751f681cf95.gif)
